name: 🐛 Bug Report
description: Report a reproducible bug or unexpected behavior
title: "[BUG]: "
labels: ["bug-fix"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short summary of the issue (this will appear after “[BUG]:”)
      placeholder: App crashes when clicking on login
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true


  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, Browser, Node version, Framework version, etc.

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs / Screenshots
      description: |
        Paste logs or drag-and-drop multiple screenshots here — GitHub will automatically upload and embed them.
      placeholder: |
        Example:
        - Error stack trace
        - Screenshot of console output

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - 🟢 Minor (doesn't block work)
        - 🟡 Major (affects main feature)
        - 🔴 Critical (blocks app or build)
    validations:
      required: true

  # - type: dropdown
  #   id: self_assign
  #   attributes:
  #     label: Would you like to work on this issue?
  #     description: Select “Yes” if you plan to fix this bug yourself.
  #     options:
  #       - "Yes, I’d like to work on this"
  #       - "No, I’m just reporting the issue"
  #   validations:
  #     required: true

  - type: markdown
    attributes:
      value: |
        ---
        ✅ **Thanks for reporting!**
        We'll review and reproduce the issue as soon as possible.
