name: 💡 Feature Request
description: Suggest a new feature, improvement, or enhancement
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request
        Have an idea for a new feature or improvement? Please describe it clearly.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Short and clear title for your feature
      placeholder: Add dark mode for dashboard
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Explain what problem or limitation this feature will solve.
      placeholder: It’s hard to read the UI at night — a dark mode would improve accessibility.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the proposed solution
      description: What do you want to happen? Be specific.
      placeholder: Add a toggle button to switch between light and dark themes, saving the preference in localStorage.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives or workarounds?
      placeholder: Using browser extensions for dark mode, but not ideal.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context / Screenshots
      description: Add any mockups, examples, or context that can help.

  - type: dropdown
    id: self_assign
    attributes:
      label: Would you like to work on this issue?
      description: Select “Yes” if you plan to implement this feature yourself.
      options:
        - "Yes, I’d like to work on this"
        - "No, I’m just suggesting the idea"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - 🟢 Low – Nice to have
        - 🟡 Medium – Would improve UX
        - 🔴 High – Important for core functionality

  - type: markdown
    attributes:
      value: |
        ---
        🚀 **Thanks for suggesting a feature!**
        We'll review your idea and discuss how it fits into our roadmap.
